### ISSUE TITLE
Consider replacing nickname with username in the chat

### ISSUE THREAD

**Issue by anyputer** [superwhiskers/reflect#2]
The current system allows for impersonation and more possibilities for people to have inappropriate names. Having the username instead, like:
```
superwhiskers#3210: hello
```
would be nicer. Admins especially would be impossible to impersonate.
```
superwhiskers#3210 (admin): hello
```
Closest thing is:
```
superwhiskers (admin)#3210: hello
```

**Comment by superwhiskers** [comment]
they already are impossible to impersonate
